version: "3.9"

networks:
  generic-backupy-api-network:
    name: generic-backupy-api-network

services:
  api:
    restart: always
    build:
      context: ..
      dockerfile: docker/python/Dockerfile
    image: generic-backupy/api
    container_name: generic-backupy-api-local
    volumes:
      - ../app:/code
      - ../redis:/redis
      - ../packages:/packages
      - ../gb_module:/gb_module
    env_file:
      - ../postgres.env
      - ../django.env
      - ../redis.env
    environment:
      - PYTHONPATH=/code:/gb_module:$PYTHONPATH
    command: uwsgi --http "0.0.0.0:8001" --module genericbackupy.wsgi --master --processes ${UWSGI_PROCESSES} --threads ${UWSGI_THREADS} --check-static /code/genericbackupy/
    ports:
      - ${API_MAPPING_PORT}:8001
    networks:
      - generic-backupy-api-network
  rq-worker:
    restart: always
    build:
      context: ..
      dockerfile: docker/python/Dockerfile
    image: generic-backupy/api
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - ../app:/code
      - ../backup_temp:/backup_temp
      - ../packages:/packages
      - ../gb_module:/gb_module
    env_file:
      - ../postgres.env
      - ../django.env
      - ../redis.env
    environment:
      - PYTHONPATH=/code:/gb_module:$PYTHONPATH
    command: python3 manage.py rqworker default --with-scheduler
    networks:
      - generic-backupy-api-network
