version: "3.9"

networks:
  generic-backupy-network-redis:
    name: generic-backupy-network-redis

volumes:
  generic-backupy-redis-volume:
    name: generic-backupy-redis-volume

services:
  redis:
    image: bitnami/redis:7.0
    user: "${UID}:${GID}"
    env_file:
      - ../redis.env
    ports:
      - ${REDIS_MAPPING_PORT}:6379
    volumes:
      - generic-backupy-redis-volume:/bitnami/redis/data
      - ../redis/tls:/tls
    networks:
      - generic-backupy-network-redis
      - restart always
