version: "3.9"

networks:
  generic-backupy-db-network:
    name: generic-backupy-db-network

volumes:
  generic-backupy-db-volume:
    name: generic-backupy-db-volume
    external: true

services:
  db:
    env_file:
      - ../postgres.env
    volumes:
      - generic-backupy-db-volume:/var/lib/postgresql/data
      - "./../server.crt:/var/lib/postgresql/server.crt:ro"
      - "./../server.key:/var/lib/postgresql/server.key:ro"
    image: postgres:14.5
    container_name: generic-backupy-api-db
    restart: always
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    ports:
      - ${POSTGRES_MAPPING_PORT}:5432
    networks:
      - generic-backupy-db-network
