# Generated by Django 3.2.16 on 2022-11-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='auth_token',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='knox.authtoken'),
            preserve_default=False,
        ),
    ]
