# Generated by Django 3.2.16 on 2022-11-22 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_backup_backupjob_backupmodule_category_storagemodule_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJobStorageModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='backupjob',
            name='storage_module',
        ),
        migrations.AddField(
            model_name='backup',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('secret', models.TextField()),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupJobStorageModuleSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('backup_job_storage_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_storage_module_secret_backup_job_storage_module', to='api.backupjobstoragemodule')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_storage_model_secret_secret', to='api.secret')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='backupjobstoragemodule',
            name='backup_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_storage_module_backup_job', to='api.backupjob'),
        ),
        migrations.AddField(
            model_name='backupjobstoragemodule',
            name='secrets',
            field=models.ManyToManyField(related_name='backup_job_storage_module_secret', through='api.BackupJobStorageModuleSecret', to='api.Secret'),
        ),
        migrations.AddField(
            model_name='backupjobstoragemodule',
            name='storage_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_storage_module_storage_module', to='api.storagemodule'),
        ),
        migrations.CreateModel(
            name='BackupJobSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_secret_backup_job', to='api.backupjob')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_secret_secret', to='api.secret')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='backupjob',
            name='backup_module_secrets',
            field=models.ManyToManyField(related_name='backup_job_secret', through='api.BackupJobSecret', to='api.Secret'),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='storage_modules',
            field=models.ManyToManyField(related_name='backup_job_storage_modules', through='api.BackupJobStorageModule', to='api.StorageModule'),
        ),
    ]
