# Generated by Django 3.2.16 on 2022-11-22 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221122_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(default=1)),
                ('output', models.TextField(blank=True, null=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.backupjob')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('involved_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.backup')),
                ('storage_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storagemodule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(default=1)),
                ('output', models.TextField(blank=True, null=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.backupjob')),
                ('backup_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.backupmodule')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
