# Generated by Django 3.2.16 on 2022-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backupexecution_storageexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupexecution',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupexecution',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
