# Generated by Django 3.2.16 on 2022-11-23 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221123_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjobstoragemodule',
            name='encryption_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_job_storage_module_encryption_secret', to='api.secret'),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('parameter', models.TextField()),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupJobStorageModuleParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('backup_job_storage_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_storage_module_parameter_backup_job_storage_module', to='api.backupjobstoragemodule')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_storage_model_parameter_parameter', to='api.parameter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupJobParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_parameter_backup_job', to='api.backupjob')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_job_parameter_parameter', to='api.parameter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='backupjob',
            name='backup_module_parameters',
            field=models.ManyToManyField(related_name='backup_job_parameter', through='api.BackupJobParameter', to='api.Parameter'),
        ),
        migrations.AddField(
            model_name='backupjobstoragemodule',
            name='parameters',
            field=models.ManyToManyField(related_name='backup_job_storage_module_parameter', through='api.BackupJobStorageModuleParameter', to='api.Parameter'),
        ),
    ]
