# Generated by Django 3.2.16 on 2022-11-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221123_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='additional_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backup',
            name='backup_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.backupexecution'),
        ),
        migrations.AddField(
            model_name='backup',
            name='storage_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storageexecution'),
        ),
    ]
