# Generated by Django 3.2.16 on 2022-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_parameter_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjobsecret',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
