# Generated by Django 3.2.16 on 2022-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_backupjobsecret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='original_file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjobstoragemodulesecret',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
