# Generated by Django 3.2.16 on 2022-12-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20221211_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='backup_module_direct_parameters',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='backupjobstoragemodule',
            name='direct_parameters',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
