# Generated by Django 3.2.16 on 2023-01-04 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230103_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='storage_module',
        ),
        migrations.AddField(
            model_name='backup',
            name='backup_job_storage_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_backup_job_storage_module', to='api.backupjobstoragemodule'),
        ),
    ]
