# Generated by Django 3.2.16 on 2023-01-07 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230104_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInstallationExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_language', models.CharField(default='en', max_length=10)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(default=0)),
                ('output', models.TextField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('backup_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.backupmodule')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('storage_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storagemodule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
