name: quality

on:
  push:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: setup env
      run: ./setup-env.sh
      shell: bash
    - name: run the tests
      run: ./manage.py.local.sh test
      shell: bash
